
import type { ItihasChapter } from './types';
import { generateContentForChapter } from './itihas-content-generator';

const chapterDetails = [
  { id: 1, title: 'Renaissance in Europe and Development of Science', description: 'The intellectual and cultural rebirth of Europe.', summary: 'The Renaissance, a fervent period of European cultural, artistic, political and economic “rebirth” following the Middle Ages, was marked by a renewed interest in classical antiquity. It witnessed groundbreaking developments in science, with figures like Copernicus and Galileo challenging established doctrines, paving the way for the Scientific Revolution. This era emphasized humanism, individualism, and a departure from medieval scholasticism towards empirical observation and inquiry.'},
  { id: 2, title: 'European Colonialism', description: 'The expansion of European powers across the globe.', summary: 'Driven by economic ambitions, religious fervor, and national rivalry, European colonialism began in the 15th century. Powers like Portugal, Spain, Britain, and France established vast overseas empires, exploiting the resources and labor of colonized lands in the Americas, Africa, and Asia. This expansion led to profound global changes, including the Columbian Exchange, the transatlantic slave trade, and the imposition of European political and cultural norms worldwide.' },
  { id: 3, title: 'India and European Colonialism', description: 'The impact of colonial rule on the Indian subcontinent.', summary: 'European colonial engagement in India began with trade, led by companies like the British East India Company. Over time, through political maneuvering and military conquest (e.g., Battle of Plassey, 1757), Britain established dominance. British rule brought significant administrative, legal, and educational changes but also led to economic exploitation, de-industrialization, and recurrent famines, fundamentally altering the subcontinent\'s trajectory.' },
  { id: 4, title: 'Colonialism and the Marathas', description: 'The Maratha Empire\'s struggle against colonial forces.', summary: 'The Maratha Empire, a dominant power in 18th-century India, posed a significant challenge to British colonial ambitions. Through a series of three Anglo-Maratha Wars, the British East India Company systematically weakened the Maratha confederacy. Despite valiant resistance, internal divisions and British military superiority ultimately led to the dissolution of the Maratha Empire by 1818, paving the way for complete British paramountcy.' },
  { id: 5, title: 'India: Social and Religious Reforms', description: 'Movements that reshaped Indian society in the 19th century.', summary: 'The 19th century witnessed a wave of social and religious reform movements in India, responding to both internal social evils and the challenge of Western modernity. Figures like Raja Ram Mohan Roy (Brahmo Samaj), Ishwar Chandra Vidyasagar, and Jyotiba Phule championed causes like the abolition of Sati, widow remarriage, women\'s education, and the eradication of caste discrimination, laying the intellectual groundwork for a modern India.' },
  { id: 6, title: 'Indian Struggle Against Colonialism', description: 'The long and varied fight for freedom from British rule.', summary: 'The Indian struggle for independence was a multi-faceted movement spanning decades. It ranged from early uprisings and the pivotal Revolt of 1857 to the moderate and extremist phases of the Indian National Congress. The Gandhian era introduced mass mobilization through non-violent methods like the Non-Cooperation, Civil Disobedience, and Quit India movements, ultimately leading to independence in 1947.' },
  { id: 7, title: 'Decolonisation to Political Integration of India', description: 'The process of becoming a unified, independent nation.', summary: 'After independence in 1947, India faced the monumental task of decolonisation and political integration. This involved the difficult process of Partition and, crucially, the integration of over 500 princely states into the Indian Union, a feat largely accomplished through the diplomatic efforts of Sardar Vallabhbhai Patel. This period established the political boundaries and federal structure of modern India.' },
  { id:8, title: 'World Wars and India', description: 'India\'s role and the impact of the two World Wars.', summary: 'India, as part of the British Empire, made significant contributions to both World War I and World War II in terms of soldiers, resources, and finances. This involvement had a profound impact, leading to economic strain, political awakening, and strengthening the demand for self-rule. The promises made by the British during the wars, and their subsequent failure to deliver, further fueled the independence movement.' },
  { id: 9, title: 'World: Decolonisation', description: 'The global trend of decolonisation in Asia and Africa.', summary: 'Following World War II, the global political landscape was transformed by the process of decolonisation. Weakened European empires could no longer maintain control over their colonies in Asia and Africa. A wave of independence movements, fueled by nationalism and the Cold War context, led to the emergence of dozens of new sovereign nations, reshaping international relations and giving birth to the "Third World".' },
  { id: 10, title: 'Cold War', description: 'The ideological and political rivalry between the USA and the USSR.', summary: 'The Cold War (c. 1947–1991) was a period of geopolitical tension between the United States (and its Western allies) and the Soviet Union (and its Eastern Bloc allies). It was characterized by an arms race, proxy wars, and ideological conflict between capitalism and communism, but without large-scale direct fighting between the two superpowers. India co-founded the Non-Aligned Movement (NAM) to steer clear of this bipolar rivalry.' },
  { id: 11, title: 'India Transformed – Part 1', description: 'Key developments in post-independence India.', summary: 'This chapter focuses on the initial decades of independent India under leaders like Jawaharlal Nehru. Key themes include the establishment of a democratic framework through the Constitution, the policy of planned economic development via Five-Year Plans, the Non-Aligned Movement in foreign policy, and tackling challenges of poverty, linguistic reorganization of states, and conflicts with neighbors.' },
  { id: 12, title: 'India Transformed – Part 2', description: 'Continuing the story of modern India\'s transformation.', summary: 'This part covers later developments in India, including the Green Revolution, political shifts in the 1970s and 80s, and the landmark economic liberalization reforms of 1991. It explores India\'s emergence as a major IT and space power, societal changes, and its evolving role in the 21st-century global order, highlighting both achievements and persistent challenges.' },
];

export const itihasChapters: ItihasChapter[] = chapterDetails.map(chapter => ({
  id: chapter.id,
  title: chapter.title,
  description: chapter.description,
  ...generateContentForChapter(chapter.id, chapter.title, chapter.summary)
}));
